language: go
go:
- tip
deploy:
  provider: heroku
  api_key:
    secure: L+fxwtyiE5unYu7PFPgpJ4zGQvhDf0fXJ/9K54CqoxcpZGpPpiOgoTpLgxO3EM4ifSGHWtgDp0QO5MNcXI3BeyfCca0c5fFRkFV+Y26iNRfCQBC1yMgfBit18XIU+NFixZy8ospuShXPQgX1zzOQRiExjBa7iIYoKl9tf11xLiQ=
  app: go-bot-gang
